[lists]
block = [
  "https://blocklistproject.github.io/Lists/crypto.txt",
  "https://blocklistproject.github.io/Lists/fraud.txt",
  "https://blocklistproject.github.io/Lists/malware.txt",
  "https://blocklistproject.github.io/Lists/phishing.txt",
  "https://blocklistproject.github.io/Lists/ransomware.txt",
  "https://blocklistproject.github.io/Lists/scam.txt",
  "https://hole.cert.pl/domains/domains.txt",
  "https://lists.cyberhost.uk/malware.txt",
  "https://media.githubusercontent.com/media/zachlagden/Pi-hole-Optimized-Blocklists/refs/heads/main/lists/malicious.txt",
  "https://phishing.army/download/phishing_army_blocklist.txt",
  "https://raw.githubusercontent.com/cenk/trcert-malware/main/trcert-domains.txt",
  "https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt",
  "https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhosts.txt",
  "https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt",
  "https://raw.githubusercontent.com/openphish/public_feed/refs/heads/main/feed.txt",
  "https://raw.githubusercontent.com/phishdestroy/destroylist/refs/heads/main/list.txt",
  "https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt",
  "https://raw.githubusercontent.com/Zaczero/pihole-phishtank/main/hosts.txt",
  "https://threatfox.abuse.ch/downloads/hostfile",
  "https://urlhaus.abuse.ch/downloads/hostfile/",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/test.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/AssoEchap/stalkerware-indicators.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/bigdargon/hostsVN.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/blocklistproject/malware.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/DandelionSprout-AntiMalwareHosts.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/disconnectme/simple-malvertising.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/malware-filter/urlhaus-filter-hosts-online.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/quidsup/notrack-malware.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/reported-by-norton.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/RPiList/Malware.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/sefinek.hosts.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/Spam404/main-blacklist.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/web-attacks.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/phishing.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/blocklistproject/phishing.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/Dogino/Discord-Phishing-URLs-phishing.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/phishing.army/blocklist-extended.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/RPiList/Phishing-Angriffe.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/ransomware/blocklistproject/ransomware.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/cryptojacking/firebog/Prigent/Crypto.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/cryptojacking/hoshsadiq/adblock-nocoin-list.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/cryptojacking/Snota418/Crypto-streams.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/abuse/blocklistproject/hosts.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/abuse/urlhaus.abuse.ch/hostfile.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/fraud/blocklistproject/hosts.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/blocklistproject/scam.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/Dogino/Discord-Phishing-URLs-scam.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/durablenapkin/scamblocklist.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/jarelllama/scam.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/sefinek.hosts.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/useless-websites/jarelllama/parked-domains.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/useless-websites/sefinek.hosts.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/ometv.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/pixiv.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/suspicious/FadeMind/add-Risk.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/suspicious/firebog/w3kbl.fork.txt",
  "https://blocklist.sefinek.net/generated/v1/0.0.0.0/suspicious/sefinek.hosts.txt",
    ]
