name: Update Blocklist Daily

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 03:00 UTC
  workflow_dispatch:       # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests tomli

      - name: Run BlocklistBlaster
        run: |
          python3 blocklistblaster.py -c blocklistblaster.toml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add lists/*.txt
            git commit -m "Daily blocklist update: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push
          else
            echo "No changes to commit"
          fi
